### ISSUE TITLE
0.0.2 upgrade gives signing key change warning

### ISSUE THREAD

**Issue by anarcat** [microg/android_packages_apps_FakeStore#10]
When I try to upgrade from 0.0.1 to 0.0.2 on f-droid, I get this typical message:

"The new version is signed with a different key to the old one. To install the new version, the old one must be uninstalled first. Please do this and try again. (Note that uninstalling will erase any internal data stored by the application)."

Why did the signing key changed? Is this something to be worried about?

**Comment by mar-v-in** [comment]
The key did not change, the issue is that f-droid is not able to detect signature spoofing and assumes that the FakeStore package is signed with Google's key which is different from microG key. You can temporarily disable signature spoofing for FakeStore to verify this.

For GmsCore we work-around this issue by putting wrong meta data in the f-droid database so that it assumes the update being signed with the Google key as well. I can add the same work-around for FakeStore.

**Comment by ale5000-git** [comment]
I think it is the wrong way, it would make more sense to fix F-Droid by adding support for signature spoofing and matching only the real signature.
