### ISSUE TITLE
How would you handle In App Purchasing and License Verification

### ISSUE THREAD

**Issue by amtlib-dot-dll** [microg/android_packages_apps_FakeStore#18]
Just be curious, but would this project be able to fake IAP request? If so it would be another Lucky Patcher :joy: :joy: :joy:

**Comment by ArchangeGabriel** [comment]
You’re not on the right project I think… FakeStore is just a dummy app mocking the presence of the Google Play Store on the device.

You’re likely willing to look at Phonesky, but I honestly don’t think that @mar-v-in have plans for such features because they are clearly illegal in lot of countries and the perfect thing to do to get attention from Google.

**Comment by amtlib-dot-dll** [comment]
Ah thanks, I didn't notice that project as it has been frozen for 4 years. You're right, it's better not to attract attention of Google, because, strictly speaking microG may also be illegal (well I'm not a lawyer)

**Comment by ArchangeGabriel** [comment]
Well situation regarding μG is a bit more complicated. But yeah, we should not give reasons to Google for trying to block μG.
