### ISSUE TITLE
PlayStore Updates

### ISSUE THREAD

**Issue by Lemmie-Hollatcha** [microg/android_packages_apps_FakeStore#26]
Hi,
I have a question and I'm hoping this is the proper place to lobby it. I'm just starting my journey into google free existence and hope to learn as much as I can. I recently installed MicroG/Lineage OS on my OnePlus 6. I downloaded APK pure to download apps not available on F-droid. I see an update available for Play Store on APK pure and am wondering if I should download the update. To clarify I have not installed PlayStore nor do I wish to. I'm just wondering if this update would apply to the MicroG software and would maintain the optimum functionality for the MicroG suite. I have scoured the internet looking for a previous question/answer to match this without success. Please let me know both if I should apply this update and also how to make sure that MicroG gets it's required updates as they are released. Thank you very much.

**Comment by ArchangeGabriel** [comment]
No, you should not install the update but rather blacklist it (I’m using Aurora Store instead of APK Pure, so not sure whether this is something you can do in APK Pure). The update appears because FakeStore tries to disguise itself as the Play Store so that μG works (software using Google Play Services are looking for Playstore in addition to GMS), the inconvenient being that they appear as update as well. Same goes for microG itself, it might appear as Play Services update, that you should not install.

**Comment by ArchangeGabriel** [comment]
Also, welcome in the Google-free world. ;)

**Comment by ale5000-git** [comment]
How already said FakeStore and microG GmsCore appears as PlayStore and Google Play Services but they are different.
You shouldn't update them and if you do the update will fail so don't worry.

The only way to correctly update them is using F-Droid (with the microG repository configured).
As alternative you could also download the apk from GitHub and manually install it.
